// Command toolsdoc generates docs/TOOLS.md from the registered tool
// definitions. Because it registers the real tools, the generated
// reference cannot drift from what the server serves. CI regenerates the
// file and fails on any diff.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"

	"github.com/hexamatic/pihole-mcp/internal/pihole"
	piholeserver "github.com/hexamatic/pihole-mcp/internal/server"
	"github.com/hexamatic/pihole-mcp/internal/tools"
	"github.com/mark3labs/mcp-go/mcp"
)

// categoryNames maps the second token of a tool name to a display heading.
var categoryNames = map[string]string{
	"padd":       "Dashboard",
	"dns":        "DNS Blocking",
	"stats":      "Statistics",
	"info":       "System Info",
	"queries":    "Query Log",
	"history":    "History",
	"search":     "Search",
	"domains":    "Domains",
	"groups":     "Groups",
	"clients":    "Clients",
	"lists":      "Lists",
	"config":     "Configuration",
	"action":     "Actions",
	"network":    "Network",
	"dhcp":       "DHCP",
	"logs":       "Logs",
	"teleporter": "Teleporter",
	"auth":       "Sessions",
	"instance":   "Multi-Instance",
}

func main() {
	out := flag.String("out", "docs/TOOLS.md", "Output path for the generated reference")
	flag.Parse()

	// Pass 1: single instance — the tool set most users see, without the
	// injected "instance" parameter.
	single := register(1)
	singleNames := make(map[string]bool, len(single))
	for _, t := range single {
		singleNames[t.Name] = true
	}

	// Pass 2: two instances — captures the multi-instance-only tools.
	tools.ResetCatalogue()
	multi := register(2)

	var multiOnly []mcp.Tool
	for _, t := range multi {
		if !singleNames[t.Name] {
			multiOnly = append(multiOnly, t)
		}
	}

	doc := render(single, multiOnly)
	//nolint:gosec // a committed documentation file must be world-readable
	if err := os.WriteFile(*out, []byte(doc), 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d tools + %d multi-instance-only)\n", *out, len(single), len(multiOnly))
}

// register builds a server against n fake instances and returns the
// recorded tool catalogue. Registration performs no network calls.
func register(n int) []mcp.Tool {
	instances := make([]pihole.InstanceConfig, n)
	for i := range instances {
		instances[i] = pihole.InstanceConfig{
			Name:     fmt.Sprintf("instance-%d", i+1),
			URL:      fmt.Sprintf("http://pihole-%d.invalid", i+1),
			Password: "unused",
		}
	}
	registry := pihole.NewRegistry(instances)
	defer registry.Close()
	_ = piholeserver.New(registry)
	return tools.Catalogue()
}

func render(single, multiOnly []mcp.Tool) string {
	var b strings.Builder

	b.WriteString("# Tool Reference\n\n")
	b.WriteString("<!-- Generated by `just docs-gen` (cmd/toolsdoc). Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "%d tools with a single Pi-hole configured; %d with multiple instances.\n\n",
		len(single), len(single)+len(multiOnly))
	b.WriteString("With more than one Pi-hole configured, every tool also accepts an optional " +
		"`instance` parameter (an instance name, or `all` to aggregate across instances), " +
		"and the tools under [Multi-Instance](#multi-instance) become available.\n\n")

	// Group in registration order.
	var order []string
	grouped := map[string][]mcp.Tool{}
	add := func(ts []mcp.Tool) {
		for _, t := range ts {
			cat := category(t.Name)
			if _, seen := grouped[cat]; !seen {
				order = append(order, cat)
			}
			grouped[cat] = append(grouped[cat], t)
		}
	}
	add(single)
	add(multiOnly)

	for _, cat := range order {
		fmt.Fprintf(&b, "## %s\n\n", cat)
		for _, t := range grouped[cat] {
			writeTool(&b, t)
		}
	}
	return b.String()
}

func category(name string) string {
	parts := strings.SplitN(name, "_", 3)
	if len(parts) < 2 {
		return "Other"
	}
	if display, ok := categoryNames[parts[1]]; ok {
		return display
	}
	return "Other"
}

func writeTool(b *strings.Builder, t mcp.Tool) {
	fmt.Fprintf(b, "### `%s`\n\n", t.Name)

	var badges []string
	if t.Annotations.ReadOnlyHint != nil && *t.Annotations.ReadOnlyHint {
		badges = append(badges, "read-only")
	}
	if t.Annotations.DestructiveHint != nil && *t.Annotations.DestructiveHint {
		badges = append(badges, "destructive")
	}
	if t.OutputSchema.Type != "" || t.RawOutputSchema != nil {
		badges = append(badges, "structured output")
	}
	if len(badges) > 0 {
		fmt.Fprintf(b, "*%s*\n\n", strings.Join(badges, " · "))
	}

	if t.Description != "" {
		fmt.Fprintf(b, "%s\n\n", t.Description)
	}

	writeParams(b, t)
}

func writeParams(b *strings.Builder, t mcp.Tool) {
	props := t.InputSchema.Properties
	if len(props) == 0 {
		b.WriteString("_No parameters._\n\n")
		return
	}

	required := make(map[string]bool, len(t.InputSchema.Required))
	for _, r := range t.InputSchema.Required {
		required[r] = true
	}

	// Required parameters first (schema order), then optional alphabetically.
	names := append([]string(nil), t.InputSchema.Required...)
	var optional []string
	for name := range props {
		// The injected multi-instance routing parameter is documented once
		// in the header, not per tool.
		if name == "instance" || required[name] {
			continue
		}
		optional = append(optional, name)
	}
	sort.Strings(optional)
	names = append(names, optional...)

	b.WriteString("| Parameter | Type | Required | Description |\n|---|---|---|---|\n")
	for _, name := range names {
		prop, ok := props[name].(map[string]any)
		if !ok {
			continue
		}
		req := "No"
		if required[name] {
			req = "Yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n",
			name, cell(propType(prop)), req, cell(propDescription(prop)))
	}
	b.WriteString("\n")
}

// propType renders the parameter type, folding in enum options.
func propType(prop map[string]any) string {
	typ, _ := prop["type"].(string)
	if typ == "" {
		typ = "any"
	}
	if enum, ok := prop["enum"].([]any); ok && len(enum) > 0 {
		opts := make([]string, len(enum))
		for i, v := range enum {
			opts[i] = fmt.Sprintf("`%v`", v)
		}
		return typ + " (" + strings.Join(opts, ", ") + ")"
	}
	return typ
}

// propDescription renders the description, folding in the default value.
func propDescription(prop map[string]any) string {
	desc, _ := prop["description"].(string)
	if def, ok := prop["default"]; ok {
		if desc != "" && !strings.HasSuffix(desc, ".") {
			desc += "."
		}
		desc = strings.TrimSpace(desc + fmt.Sprintf(" Default: `%v`.", def))
	}
	return desc
}

// cell escapes a value for use inside a Markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.ReplaceAll(s, "\n", " ")
}
